macro(_sbeParseObject prefix)
  math(EXPR object_depth "${object_depth} + 1")  
  if(${object_depth})
    list(APPEND ${json_AllVariables} ${prefix})
  endif()
  _sbeParse(${prefix})
  _sbeMoveToNextNonEmptyCharacter()
  math(EXPR object_depth "${object_depth} - 1")    
endmacro()
