include(Backports/IncludeGuard)
include_guard(GLOBAL)

include(Fortran/Backtrace)
include(Fortran/Standard)
include(Fortran/TempArrays)
include(Fortran/NoBackslashEscape)
include(Fortran/Integer)
include(Fortran/Real)
include(Fortran/StandardAdherence)
include(Fortran/ModuleDirectory)
