include(Backports/IncludeGuard)
include_guard(GLOBAL)

include(FunctionExtension/push)
include(FunctionExtension/pop)
include(FunctionExtension/call)
include(FunctionExtension/backup)
include(FunctionExtension/add_library)
include(FunctionExtension/add_executable)
include(FunctionExtension/set_property)
include(FunctionExtension/set_target_properties)
include(FunctionExtension/target_sources)
include(FunctionExtension/find_package)
include(FunctionExtension/set_target_properties)
