macro(sbeParseJson prefix jsonString)
  cmake_policy(PUSH)
  
  set(json_string "${${jsonString}}")
  string(LENGTH "${json_string}" json_jsonLen)
  set(json_index 0)
  set(object_depth -1)
  set(json_AllVariables ${prefix})
  set(json_ArrayNestingLevel 0)
  set(json_MaxArrayNestingLevel 0)
  
  _sbeParse(${prefix})
  
  unset(json_index)
  unset(object_depth)
  unset(json_AllVariables)
  unset(json_jsonLen)
  unset(json_string)
  unset(json_value)
  unset(json_inValue)    
  unset(json_name)
  unset(json_inName)
  unset(json_newPrefix)
  unset(json_reservedWord)
  unset(json_arrayIndex)
  unset(json_char)
  unset(json_end)
  unset(json_ArrayNestingLevel)
  foreach(json_nestingLevel RANGE ${json_MaxArrayNestingLevel})
    unset(json_${json_nestingLevel}_arrayIndex)
  endforeach()
  unset(json_nestingLevel)
  unset(json_MaxArrayNestingLevel)
  
  cmake_policy(POP)
  
endmacro()
